version: "3.9"
services:
  php:
    image: lavoweb/php-5.4
    ports:
      - 80:80
    volumes:
      # chmod 777 public/zdjecia
      - .:/var/www/html/
    links:
      - db:db
  db:
    image: mariadb:10.1.48
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pilka-nozna
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.0.4
    ports:
      - 8080:80
    links:
      - db:db
volumes:
  data:

